# Generated by Django 5.1 on 2024-11-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_post_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
